#!/usr/bin/env python3
"""
Pikkolo Mesh Stick Rev B — schematic source.

Generates mesh.kicad_sch. Connectivity lives here; schlib.py turns it into KiCad and
layout.py provides the drawing shapes. Regenerating overwrites the .kicad_sch, so once
you start editing in Eeschema this file becomes a reference rather than the source.

Rev B changes from Rev A:
  - USB-A edge fingers replaced by a real USB-C male plug (J2), with the Rd pull-down
    the Type-C spec requires of a sink presenting a plug. This also frees the board
    from the 2.0 mm thickness that only the USB-A fingers needed.
  - RF network, power chain and level shifter drawn as wired chains rather than as
    free-floating parts joined only by labels.

Provenance tags on nets and values:
  [variant]  verbatim from Meshtastic variants/rp2040/rp2040-lora/variant.h
  [chosen]   not in that file; needs a variant patch (see docs/SCHEMATIC-NOTES.md)
  [semtech]  SX1262 datasheet Rev 2.2 / AN1200.40 reference-design topology
  [ws]       value from the Waveshare RP2040-LoRa schematic, the board this clones
  [rpi]      Raspberry Pi "Hardware design with RP2040" minimal design
  [usbc]     USB Type-C Cable and Connector Specification
"""
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from schlib import Sch
from layout import Chain

REV = "B"
DATE = "2026-08-23"

FP = dict(
    RP2040="zach:RP2040-QFN-56-1EP_7x7mm_P0.4mm_EP-vias",
    SX1262="zach:SX1262-QFN-24-1EP_4x4mm_P0.5mm_EP-vias",
    SOIC8="Package_SO:SOIC-8_5.3x5.3mm_P1.27mm",
    SC70_6="Package_TO_SOT_SMD:SOT-363_SC-70-6",
    SOT23_5="Package_TO_SOT_SMD:SOT-23-5",
    SOT23_6="Package_TO_SOT_SMD:SOT-23-6",
    XTAL="Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
    TCXO="Oscillator:Oscillator_SMD_SeikoEpson_TG2520SMN-xxx-xxxxxx-4Pin_2.5x2.0mm",
    LED="LED_SMD:LED_0603_1608Metric",
    SW="Button_Switch_SMD:SW_Push_1P1T_XKB_TS-1187A",
    USBC="Connector_USB:USB_C_Plug_JAE_DX07P024AJ1",
    SMA="Connector_Coaxial:SMA_Amphenol_132289_EdgeMount",
    TP="TestPoint:TestPoint_Pad_D1.0mm",
    R="Resistor_SMD:R_0402_1005Metric",
    C="Capacitor_SMD:C_0402_1005Metric",
    C0603="Capacitor_SMD:C_0603_1608Metric",
    C0805="Capacitor_SMD:C_0805_2012Metric",
    L="Inductor_SMD:L_0402_1005Metric",
    FB="Inductor_SMD:L_0603_1608Metric",
)

s = Sch(paper="A2", project="mesh", title="Pikkolo Mesh Stick", rev=REV, date=DATE,
        comments=["RP2040 + SX1262 US915 Meshtastic node, USB-C stick form",
                  "Generated by mesh_design.py - do not hand-edit while that is the source",
                  "Verified by verify_netlist.py and check_design.py"])
R_, C_, L_ = "Device:R", "Device:C", "Device:L"


def cap(ref, x, y, val, fp=FP["C"], angle=0, **kw):
    s.place(ref, C_, x, y, value=val, footprint=fp, angle=angle, **kw)


def res(ref, x, y, val, dnp=False, angle=0, **kw):
    s.place(ref, R_, x, y, value=val, footprint=FP["R"], dnp=dnp, angle=angle, **kw)


def ind(ref, x, y, val, angle=0, **kw):
    s.place(ref, L_, x, y, value=val, footprint=FP["L"], angle=angle, **kw)


def flag(ref, x, y):
    s.place(ref, "power:PWR_FLAG", x, y, in_bom=False)


def rail(ref, lib, x, y):
    s.place(ref, lib, x, y, in_bom=False)


def decouple(ref, x, y, val, node, fp=FP["C"], at=None):
    """
    A bypass cap from `node` to ground, drawn vertically.

    `at` records which pin the cap belongs to. Stacked symbol pins collapse a whole
    rail onto one schematic node, so without this the layout has no way to know that
    C3..C9 are one-per-IOVDD-pin rather than six caps that may all go on one side.
    """
    cap(ref, x, y, val, fp=fp, props={"Description": "decoupling: %s" % at} if at else None)
    s.net(node, "%s.1" % ref)
    s.net("GND", "%s.2" % ref)


def series(ref, kind, x, y, val, a, b, angle=0):
    """A series element bridging nets `a` and `b`, joined only by its labels."""
    (cap if kind == "C" else ind if kind == "L" else res)(ref, x, y, val, angle=angle)
    s.net(a, "%s.1" % ref)
    s.net(b, "%s.2" % ref)


# ================================================ A. USB-C entry, ESD, power rails
s.box(12.7, 15.24, 187.96, 154.94)
s.text(15.24, 22.86, "A  USB-C plug entry, ESD, power rails")

# J2 is a USB-C PLUG on the board: this stick IS the plug. A sink presenting a plug
# terminates CC with a single Rd; putting Rd on both CC and VCONN would show the host
# the Debug-Accessory signature instead of a device.  [usbc]
# This is a straddle-mount plug: the A row lands on F.Cu, the B row on B.Cu, and the
# board edge itself becomes the plug's tongue. So the CONNECTOR sets the stack-up --
# JAE's drawing calls for 0.8 +/-0.08 mm pad to pad. That is also what makes a 90 ohm
# USB pair and a sane 50 ohm RF line routable on two layers.  [usbc]
s.place("J2", "Connector:USB_C_Plug_USB2.0", 38.1, 71.12, value="USB-C plug",
        footprint=FP["USBC"])
s.net("VBUS", "J2.A4")                     # A4/A9/B4/B9 are one stacked pin
s.net("GND", "J2.A1", "J2.SH")             # A1/A12/B1/B12 stacked; shell to GND
s.net("USB_CC", "J2.A5")
s.net("USB_DP_C", "J2.A6")
s.net("USB_DM_C", "J2.A7")
s.no_connect("J2.B5")                      # VCONN must read above zOPEN=126k: leave open  [usbc]
# B6/B7 are absent from a USB 2.0 plug by spec (Table 3-11 note 2) and the receptacle
# already shorts A6<->B6, so do not tie them "for symmetry" -- that is a stub on a 90 ohm
# pair. SBU1/SBU2 must read >=950k, and the SuperSpeed pads must float: grounding them
# would short the host's TX/RX. All are left off the netlist on purpose.  [usbc]

res("R11", 71.12, 78.74, "5k1")            # Rd, 5.1k 1% -- the +/-10% row of Table 4-28  [usbc]
s.net("USB_CC", "R11.1")
s.net("GND", "R11.2")

s.place("U7", "Power_Protection:USBLC6-2SC6", 106.68, 66.04, value="USBLC6-2SC6",
        footprint=FP["SOT23_6"])
s.net("USB_DP_C", "U7.1")
s.net("USB_DM_C", "U7.3")
s.net("VBUS", "U7.5")
s.net("GND", "U7.2")
s.net("USB_DP_R", "U7.6")
s.net("USB_DM_R", "U7.4")
decouple("C41", 137.16, 88.9, "100n", "VBUS", at="U7 pin 5 VBUS clamp")

res("R1", 147.32, 60.96, "27R", angle=90)  # RP2040 USB series terminations  [rpi]
res("R2", 147.32, 71.12, "27R", angle=90)
s.net("USB_DP_R", "R1.1")
s.net("USB_DM_R", "R2.1")
s.net("USB_DP", "R1.2")
s.net("USB_DM", "R2.2")

rail("#PWR_VBUS", "power:VBUS", 71.12, 45.72)
s.net("VBUS", "#PWR_VBUS.1")
flag("#FLG_VBUS", 88.9, 45.72)
s.net("VBUS", "#FLG_VBUS.1")
flag("#FLG_GND", 17.78, 60.96)
s.net("GND", "#FLG_GND.1")
rail("#PWR_GND1", "power:GND", 17.78, 71.12)
s.net("GND", "#PWR_GND1.1")

# --- VBUS -> ferrite -> the two 3V3 rails ---------------------------------
s.place("FB1", "Device:FerriteBead", 45.72, 116.84, value="600R@100MHz",
        footprint=FP["FB"], angle=90)
s.net("VBUS", "FB1.1")
s.net("VBUS_F", "FB1.2")
flag("#FLG_VBUSF", 22.86, 116.84)
s.net("VBUS_F", "#FLG_VBUSF.1")
# Total VBUS-to-GND capacitance is capped at 10uF by BOTH USB 2.0 (inrush, section
# 7.2.4.1) and Type-C (Table 4-3). The ferrite does not buy an exemption: at ~0.3 ohm DCR
# everything behind it is visible on the inrush timescale. Budget, in uF:
#   C26 4.7 + C27 1 + C15 1 + C41 0.1 + C38 0.1 + C39 2.2 = 9.1uF.  [usbc]
decouple("C26", 33.02, 132.08, "4u7", "VBUS", fp=FP["C0603"])
decouple("C27", 60.96, 132.08, "1u", "VBUS_F")

s.place("U5", "Regulator_Linear:ME6211C33M5", 111.76, 116.84, value="ME6211C33M5G",
        footprint=FP["SOT23_5"])
s.net("VBUS_F", "U5.1", "U5.3")            # CE tied to VIN: always on
s.net("GND", "U5.2")
s.net("+3V3", "U5.5")
s.no_connect("U5.4")
decouple("C15", 91.44, 132.08, "1u", "VBUS_F")
decouple("C16", 137.16, 132.08, "1u", "+3V3")
decouple("C18", 157.48, 132.08, "10u", "+3V3", fp=FP["C0603"])
rail("#PWR_3V3A", "power:+3V3", 177.8, 116.84)
s.net("+3V3", "#PWR_3V3A.1")

s.place("U6", "Regulator_Linear:LP5907MFX-3.3", 111.76, 152.4, value="LP5907MFX-3.3",
        footprint=FP["SOT23_5"])
s.net("VBUS_F", "U6.1", "U6.3")
s.net("GND", "U6.2")
s.net("+3V3_RF", "U6.5")
s.no_connect("U6.4")
decouple("C17", 137.16, 167.64, "1u", "+3V3_RF")
decouple("C19", 157.48, 167.64, "10u", "+3V3_RF", fp=FP["C0603"])
decouple("C14", 91.44, 167.64, "100n", "+3V3_RF")
rail("#PWR_RFA", "zach:+3V3_RF", 177.8, 152.4)
s.net("+3V3_RF", "#PWR_RFA.1")

# ================================================== B. RP2040, flash, crystal, buttons
s.box(208.28, 15.24, 210.82, 279.4)
s.text(210.82, 22.86, "B  RP2040, QSPI flash, crystal, buttons")

# Pin 57, the centre pad, is the RP2040's ONLY ground connection. The stock KiCad
# footprint puts no vias in it, which on two layers leaves every return current looking
# for a path to the bottom pour that somebody has to remember to draw.
s.place("U1", "MCU_RaspberryPi:RP2040", 281.94, 132.08, value="RP2040",
        footprint=FP["RP2040"])

s.net("+3V3", "U1.1", "U1.43", "U1.44", "U1.48")   # IOVDD(x6 stacked), ADC_AVDD, VREG_VIN, USB_VDD
s.net("DVDD", "U1.23", "U1.45")                    # VREG_VOUT feeds DVDD  [rpi]
s.net("GND", "U1.57", "U1.19")                     # TESTEN must be grounded  [rpi]
s.net("USB_DM", "U1.46")
s.net("USB_DP", "U1.47")
s.net("RUN", "U1.26")

# 100nF per power pin [rpi]; schematically one node, physically one cap per pin.
# 100nF per power pin [rpi]. The IOVDD pins are stacked in the symbol, so the pin each
# cap belongs to is recorded in its Description rather than being visible in the ratsnest.
for ref, x, pin in [("C3", 218.44, "IOVDD pin 1"), ("C4", 233.68, "IOVDD pin 10"),
                    ("C5", 248.92, "IOVDD pin 22"), ("C6", 264.16, "IOVDD pin 33"),
                    ("C8", 279.4, "IOVDD pin 42"), ("C9", 294.64, "IOVDD pins 48+49"),
                    ("C44", 309.88, "ADC_AVDD pin 43")]:
    decouple(ref, x, 40.64, "100n", "+3V3", at=pin)
# The core LDO needs 1uF at BOTH ends: VREG_VIN also feeds the power-on-reset and
# brown-out blocks, so noise there shows up as unexplained resets.  [rpi]
decouple("C42", 325.12, 40.64, "1u", "+3V3", at="VREG_VIN pin 44")
decouple("C7", 340.36, 40.64, "100n", "DVDD", at="DVDD pin 23")
decouple("C43", 355.6, 40.64, "100n", "DVDD", at="DVDD pin 50")
decouple("C28", 370.84, 40.64, "1u", "DVDD", at="VREG_VOUT pin 45")

res("R5", 226.06, 96.52, "10k")                    # RUN pull-up  [rpi]
s.net("+3V3", "R5.1")
s.net("RUN", "R5.2")

# 12MHz crystal. Raspberry Pi's validated combination is a CL=10pF part with 15p loads
# and 1k in series: 15p||15p = 7.5p, +3p stray = 10.5p ~= CL. The 27p this carried before
# implies CL=16.5pF, which matches no specified crystal and eats start-up margin.  [rpi]
s.place("Y1", "Device:Crystal_GND24", 231.14, 187.96, value="12MHz CL10p",
        footprint=FP["XTAL"], props={"MPN": "ABM8-272-T3", "Manufacturer": "Abracon"})
res("R3", 254.0, 187.96, "1k")
cap("C1", 220.98, 205.74, "15p")
cap("C2", 251.46, 205.74, "15p")
s.net("XIN", "U1.20", "Y1.1", "C1.1")
s.net("XOUT_R", "Y1.3", "C2.1", "R3.1")
s.net("XOUT", "R3.2", "U1.21")
s.net("GND", "C1.2", "C2.2", "Y1.2")

# QSPI flash
s.place("U3", "zach:GD25Q32E", 355.6, 187.96, value="GD25Q32E", footprint=FP["SOIC8"])
decouple("C12", 388.62, 187.96, "100n", "+3V3")
s.net("+3V3", "U3.8")
s.net("GND", "U3.4")
s.net("QSPI_SS", "U1.56", "U3.1")
s.net("QSPI_SCLK", "U1.52", "U3.6")
s.net("QSPI_SD0", "U1.53", "U3.5")
s.net("QSPI_SD1", "U1.55", "U3.2")
s.net("QSPI_SD2", "U1.54", "U3.3")
s.net("QSPI_SD3", "U1.51", "U3.7")

# CS# must be at its own supply as the flash powers up, and RP2040's internal pull-up is
# not active until POR completes. RPi omit this only for a flash they qualified; the
# GD25Q32E is not that part.  [rpi]
res("R14", 314.96, 220.98, "10k")
s.net("+3V3", "R14.1")
s.net("QSPI_SS", "R14.2")

# BOOTSEL pulls QSPI_SS low through 1K -- with R14 fitted the divider gives 0.30V  [rpi]
res("R4", 332.74, 246.38, "1k", angle=90)
s.net("QSPI_SS", "R4.1")
s.place("TP5", "Connector:TestPoint", 358.14, 246.38, value="BOOTSEL", footprint=FP["TP"])
s.net("BOOT_SW", "R4.2", "TP5.1")

# User button on GPIO6  [chosen] — the stock variant sets BUTTON_PIN -1
s.place("SW1", "Switch:SW_Push", 355.6, 274.32, value="USER", footprint=FP["SW"])
s.net("BTN_USER", "SW1.1", "U1.8")
s.net("GND", "SW1.2")

s.place("TP1", "Connector:TestPoint", 226.06, 246.38, value="SWCLK", footprint=FP["TP"])
s.place("TP2", "Connector:TestPoint", 246.38, 246.38, value="SWDIO", footprint=FP["TP"])
s.place("TP3", "Connector:TestPoint", 266.7, 246.38, value="GND", footprint=FP["TP"])
s.place("TP4", "Connector:TestPoint", 287.02, 246.38, value="RUN", footprint=FP["TP"])
s.net("RUN", "TP4.1")
s.place("TP6", "Connector:TestPoint", 307.34, 246.38, value="SDA", footprint=FP["TP"])
s.place("TP7", "Connector:TestPoint", 327.66, 246.38, value="SCL", footprint=FP["TP"])
s.net("I2C_SDA", "U1.6", "TP6.1")                  # GPIO4 = Wire0 SDA
s.net("I2C_SCL", "U1.7", "TP7.1")                  # GPIO5 = Wire0 SCL
s.net("SWCLK", "U1.24", "TP1.1")
s.net("SWDIO", "U1.25", "TP2.1")
s.net("GND", "TP3.1")

# ============================================================ C. SX1262 + TCXO
s.box(429.26, 15.24, 152.4, 154.94)
s.text(431.8, 22.86, "C  SX1262 + 32MHz TCXO")

# The exposed pad is both the thermal path for ~230 mW at +22 dBm and the radio's whole
# ground return on two layers, so the footprint carries its own vias.  [semtech]
s.place("U2", "RF:SX1262IMLTRT", 490.22, 106.68, value="SX1262IMLTRT",
        footprint=FP["SX1262"])

# VDD_IN (1) ties straight to VBAT (10); VBAT_IO (11) shares the SAME rail so the
# datasheet rule "VBAT_IO <= VBAT at all times" cannot be broken by LDO ramp skew.
decouple("C10", 439.42, 40.64, "100n", "+3V3_RF", at="VDD_IN/VBAT pins 1/10/11 HF")
decouple("C11", 454.66, 40.64, "1u", "+3V3_RF", at="VBAT/VBAT_IO bulk for the PA step")
decouple("C29", 469.9, 40.64, "470n", "SX_VREG")   # VREG  [ws]
decouple("C30", 485.14, 40.64, "47n", "VR_PA")     # VR_PA coarse  [ws]
decouple("C37", 500.38, 40.64, "47p", "VR_PA")     # VR_PA fine  [ws]
s.net("+3V3_RF", "U2.1", "U2.10", "U2.11")
s.net("GND", "U2.2")
s.net("SX_VREG", "U2.7")
s.net("VR_PA", "U2.24")
# Internal-LDO mode, Option D of datasheet Fig 5-4. Meshtastic/RadioLib issue
# SetRegulatorMode(DC-DC) unconditionally with no build flag to change it, but the
# datasheet is explicit that the linear regulator backstops VREG, and Meshtastic's own
# shipping t-echo-lite variant leaves DCC_SW open the same way. The cost is 4.2 mA more
# in RX, which is free on a USB-powered stick, and it saves the 15uH inductor.  [semtech]
s.no_connect("U2.9")

# SPI1 + control  [variant]
s.net("LORA_SCK", "U2.18", "U1.17")                # GPIO14
s.net("LORA_MOSI", "U2.17", "U1.18")               # GPIO15
s.net("LORA_MISO", "U2.16", "U1.36")               # GPIO24
s.net("LORA_CS", "U2.19", "U1.16")                 # GPIO13
s.net("LORA_RST", "U2.15", "U1.35")                # GPIO23
s.net("LORA_BUSY", "U2.14", "U1.29")               # GPIO18
s.net("LORA_DIO1", "U2.13", "U1.27")               # GPIO16

# TCXO. Semtech requires a 10pF DC-cut in series with 220R into XTA, and XTB open.
# Waveshare uses a bare 0R with no DC block; follow Semtech, not Waveshare.  [semtech]
# Pin 1 of a clipped-sine TCXO is NC, not an enable -- the ASE-xxxMHz symbol this used to
# carry is an HCMOS oscillator, and driving its pin 1 high was wiring an enable that the
# real part does not have. The 2520 body is also where the cheap 32 MHz parts live.
s.place("Y2", "Oscillator:TG2520SMN-xx.xxxxxxMhz-xxxxNM", 439.42, 137.16,
        value="32MHz TCXO 1.8V clipped-sine", footprint=FP["TCXO"],
        props={"MPN": "TG2520SMN 32.0000M", "Manufacturer": "Seiko Epson",
               "LCSC": "C7527388",
               "Description": "32.000MHz TCXO, clipped sine 0.2-1.2Vpp, Vcc 1.7-3.6V, "
                              "ICC <=3mA, start-up <=5ms (RadioLib gates at 5ms), "
                              "stability <=+/-2ppm"})
decouple("C13", 439.42, 162.56, "100n", "VDD_TCXO")
series("R6", "R", 469.9, 129.54, "220R", "TCXO_OUT", "TCXO_AC", angle=90)
series("C40", "C", 485.14, 129.54, "10p", "TCXO_AC", "XTA", angle=90)
s.quiet_pin("C40.1")
s.net("XTA", "U2.3")
s.net("VDD_TCXO", "U2.6", "Y2.4")                  # DIO3 is a programmable LDO
s.no_connect("Y2.1")                               # NC on a TCXO: open or GND, never driven
s.net("TCXO_OUT", "Y2.3")
s.net("GND", "Y2.2")
s.no_connect("U2.4")                               # XTB left open with a TCXO  [semtech]
flag("#FLG_TCXO", 515.62, 162.56)
s.net("VDD_TCXO", "#FLG_TCXO.1")

# ====================================================== D. RF front end (915MHz)
s.box(12.7, 302.26, 447.04, 101.6)
s.text(15.24, 309.88,
       "D  TX LPF / RX balun / antenna pi / SPDT     values [ws] 902-928MHz - tune on hardware")

RFFP = dict(R=FP["R"], C=FP["C"], L=FP["L"])
TXY, RXY = 342.9, 383.54

# --- TX arm: RFO -> 2nd-harmonic notch -> pi LPF -> switch RF1 --------------
tx = Chain(s, 40.64, TXY, RFFP)
tx.series("L1", "L", "47n", "VR_PA", "RFO")        # PA drain choke  [semtech]
tx.series("L2", "L", "2n5", "RFO", "TX1")
tx.series("C22", "C", "39p", "TX1", "TX2")         # DC block into the switch
tx.series("L3", "L", "4n7", "TX2", "RF_TX")
tx.parallel("C20", "C", "3p", "RFO", "TX1")        # notch at the 2nd harmonic
tx.shunt("C21", "C", "5p6", "TX1")
tx.shunt("C23", "C", "1p8", "RF_TX")
s.net("RFO", "U2.23")

# --- RX arm: switch RF2 -> lumped balun -> differential LNA -----------------
rx = Chain(s, 116.84, RXY, RFFP, mirror=True)
rx.series("C25", "C", "2p4", "RF_RX", "RFI_N")
rx.series("L4", "L", "15n", "RFI_N", "RFI_P")
rx.shunt("C24", "C", "1p", "RF_RX")
rx.shunt("C31", "C", "1p8", "RFI_P")
s.net("RFI_N", "U2.22")
s.net("RFI_P", "U2.21")

# --- SPDT switch, complementary control  [variant] -------------------------
s.place("U4", "zach:PE4259-63", 190.5, 358.14, value="PE4259-63", footprint=FP["SC70_6"])
s.net("RF_TX", "U4.1")                             # RF1 = TX  [semtech]
s.net("RF_RX", "U4.3")                             # RF2 = RX
s.net("RF_ANT", "U4.5")
s.net("GND", "U4.2")
series("R7", "R", 149.86, 337.82, "100R", "RF_SW_CTRL", "SW_CTRL", angle=90)
series("R8", "R", 149.86, 388.62, "100R", "RF_SW_NCTRL", "SW_NCTRL", angle=90)
s.net("SW_CTRL", "U4.4")
s.net("SW_NCTRL", "U4.6")
decouple("C35", 165.1, 325.12, "1n", "SW_CTRL")
decouple("C36", 165.1, 396.24, "1n", "SW_NCTRL")
s.net("RF_SW_CTRL", "U2.12")                       # DIO2 drives CTRL
s.net("RF_SW_NCTRL", "U1.28")                      # GPIO17 drives the complement

# --- antenna pi, then the build-time IFA / SMA selection -------------------
ant = Chain(s, 259.08, TXY, RFFP)
ant.series("C32", "C", "39p", "RF_ANT", "ANT1")    # DC block off RFC
ant.series("L5", "L", "9n1", "ANT1", "ANT2")
ant.shunt("C33", "C", "3p9", "ANT1")
ant.shunt("C34", "C", "3p9", "ANT2")

# Single antenna feed. A printed IFA at 915 MHz is 43 x 20 mm (TI DN023) and would eat
# 57% of the board while still needing retuning against a ground plane half the size TI
# characterised. The dual-feed 0R pair went with it: two stubs off ANT2 detune whichever
# feed is actually fitted, and the two feeds want incompatible board-end treatments.
s.place("J1", "Connector:Conn_Coaxial", 320.04, TXY, value="SMA edge", footprint=FP["SMA"])
s.net("ANT2", "J1.1")
s.net("GND", "J1.2")

# ================================================ E. Status LEDs
s.box(12.7, 177.8, 187.96, 114.3)
s.text(15.24, 185.42, "E  Status LEDs: heartbeat and radio activity")

# Two plain LEDs, not the SK9822 this carried before. Upstream Meshtastic drives LED_POWER
# (a 1 ms heartbeat once a second) and LED_LORA (solid through TX, 100 ms on each received
# packet) from single GPIOs with nothing but a #define -- there is no APA102/SK9822 driver
# in the tree at all, and AmbientLightingThread only knows NCP5623, LP5562 and NeoPixel.
# This also deletes the board's only 4.5-5.5 V logic domain and its only part with under
# 500 pieces of distributor stock.
s.place("D1", "Device:LED", 63.5, 213.36, value="green", footprint=FP["LED"], angle=180)
res("R9", 78.74, 213.36, "1k", angle=90)
s.net("LED_PWR", "U1.4", "D1.2")                   # GPIO2 -> anode, LED_POWER heartbeat
s.net("LED_PWR_K", "D1.1", "R9.1")                 # cathode -> 1k -> GND
s.net("GND", "R9.2")
s.quiet_pin("R9.1")

s.place("D2", "Device:LED", 63.5, 241.3, value="red", footprint=FP["LED"], angle=180)
res("R10", 78.74, 241.3, "1k", angle=90)
s.net("LED_LORA", "U1.5", "D2.2")                  # GPIO3 -> anode, LED_LORA activity
s.net("LED_LORA_K", "D2.1", "R10.1")               # cathode -> 1k -> GND
s.net("GND", "R10.2")
s.quiet_pin("R10.1")

# Unused GPIOs get an explicit no-connect so ERC stays meaningful.
ALL_GPIO_PINS = list(range(2, 10)) + list(range(11, 19)) + list(range(27, 33)) + \
    list(range(34, 42))
USED_GPIO_PINS = {4, 5, 6, 7, 8, 16, 17, 18, 27, 28, 29, 35, 36}
for pin in ALL_GPIO_PINS:
    if pin not in USED_GPIO_PINS:
        s.no_connect("U1.%d" % pin)

if __name__ == "__main__":
    out = pathlib.Path(__file__).parent / "mesh.kicad_sch"
    errs, warns = s.write(out)
    print("wrote %s  (%d placements, %d connections)" % (out.name, len(s.parts), len(s.conns)))
    for e in errs:
        print("  ERROR  ", e)
    for w in warns:
        print("  warn   ", w)
    import json
    (pathlib.Path(__file__).parent / "intended_netlist.json").write_text(
        json.dumps(s.intended_netlist(), indent=1))
    sys.exit(1 if errs else 0)
