#!/usr/bin/env python3
"""
Pikkolo Mesh Stick Rev B — schematic source.

Generates mesh.kicad_sch. Connectivity lives here; schlib.py turns it into KiCad and
layout.py provides the drawing shapes. Regenerating overwrites the .kicad_sch, so once
you start editing in Eeschema this file becomes a reference rather than the source.

Rev B changes from Rev A:
  - USB-A edge fingers replaced by a real USB-C male plug (J2), with the Rd pull-down
    the Type-C spec requires of a sink presenting a plug. This also frees the board
    from the 2.0 mm thickness that only the USB-A fingers needed.
  - RF network, power chain and level shifter drawn as wired chains rather than as
    free-floating parts joined only by labels.

Provenance tags on nets and values:
  [variant]  verbatim from Meshtastic variants/rp2040/rp2040-lora/variant.h
  [chosen]   not in that file; needs a variant patch (see docs/SCHEMATIC-NOTES.md)
  [semtech]  SX1262 datasheet Rev 2.2 / AN1200.40 reference-design topology
  [ws]       value from the Waveshare RP2040-LoRa schematic, the board this clones
  [rpi]      Raspberry Pi "Hardware design with RP2040" minimal design
  [usbc]     USB Type-C Cable and Connector Specification
"""
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from schlib import Sch
from layout import Chain

REV = "B"
DATE = "2026-08-23"

# Decisions that layout depends on. `None` means UNDECIDED, and ready_to_route.py fails
# the gate on any None -- so an open question cannot be forgotten into a fab order. Each
# entry records the reason, because a bare number invites someone to "improve" it later.
STACKUP = dict(
    layers=4,
    stackup_code="JLC04081H-3313",
    thickness_mm=0.8,     # set BY THE CONNECTOR: the JAE DX07P024AJ1 straddle plug
                          # specifies 0.8 +/-0.08 mm pad-to-pad, and the board edge is the
                          # plug's tongue. Not a free choice.
    l1_l2_mm=0.0994,      # 3313 prepreg, Er 4.1. The number the RF geometry hangs on:
                          # 50 ohm comes out 0.15 mm masked, narrower than the pads it
                          # lands on, instead of 1.34 mm on a 2-layer 0.8 mm board.
    copper_oz=1,          # 1 oz outer, 0.5 oz inner
    finish="ENIG",        # 0.8 mm board, 0.4 mm pitch QFN, and an RF front end
)
# Order JLC04081H-3313 BY NAME, never "no requirement". JLCPCB's finished-thickness
# tolerance (+/-0.1 mm) is wider than the connector's window (0.72-0.88 mm) and nothing
# closes that; all you can control is where the nominal sits. -3313 builds at 0.7992 mm,
# dead centre. Explicitly exclude JLC04081H-7628A, which builds at 0.7212 mm - below the
# connector's floor before tolerance is even applied.

DECISIONS = dict(
    rf_network="johanson-ipd",   # 0900FM15K0039001E -- see block D
    antenna="sma-right-angle",   # BWSMA-KWE-Z001, through-hole, thickness-agnostic
    flash_mpn="in-package",      # RP2354A stacks 2MB; there is no external flash
    rails="two-ldo",      # U6 carries the whole radio: 120 mA at +22 dBm. Worst case
                          # (5.5-3.3)*0.120 = 0.264 W into a SOT-23-5 at RthJA 193.4 C/W
                          # = 51 C rise. Acceptable, and a shared rail would put RP2040
                          # USB and QSPI switching noise onto VBAT with no headroom -- the
                          # SX1262 needs >=3.30 V at its pins to reach +22 dBm.
    ferrite_fb1=False,    # deleted: see the VBUS budget comment
)

FP = dict(
    RP2354="zach:RP2354A-QFN-60-1EP_7x7mm_P0.4mm_EP-vias",
    L3012="Inductor_SMD:L_Cenker_CKCS3012",
    SX1262="zach:SX1262-QFN-24-1EP_4x4mm_P0.5mm_EP-vias",
    SOIC8="Package_SO:SOIC-8_5.3x5.3mm_P1.27mm",
    SC70_6="Package_TO_SOT_SMD:SOT-363_SC-70-6",
    SOT23_5="Package_TO_SOT_SMD:SOT-23-5",
    SOT23_6="Package_TO_SOT_SMD:SOT-23-6",
    XTAL="Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
    TCXO="Oscillator:Oscillator_SMD_SeikoEpson_TG2520SMN-xxx-xxxxxx-4Pin_2.5x2.0mm",
    LED="LED_SMD:LED_0603_1608Metric",
    SW="Button_Switch_SMD:SW_Push_1P1T_XKB_TS-1187A",
    USBC="Connector_USB:USB_C_Plug_JAE_DX07P024AJ1",
    SMA="Connector_Coaxial:SMA_BAT_Wireless_BWSMA-KWE-Z001",
    IPD="RF_Converter:Balun_Johanson_0900FM15K0039",
    TP="TestPoint:TestPoint_Pad_D1.0mm",
    R="Resistor_SMD:R_0402_1005Metric",
    C="Capacitor_SMD:C_0402_1005Metric",
    C0603="Capacitor_SMD:C_0603_1608Metric",
    C0805="Capacitor_SMD:C_0805_2012Metric",
    L="Inductor_SMD:L_0402_1005Metric",
    FB="Inductor_SMD:L_0603_1608Metric",
)

s = Sch(paper="A2", project="mesh", title="Pikkolo Mesh Stick", rev=REV, date=DATE,
        comments=["RP2040 + SX1262 US915 Meshtastic node, USB-C stick form",
                  "Generated by mesh_design.py - do not hand-edit while that is the source",
                  "Verified by verify_netlist.py and check_design.py"])
R_, C_, L_ = "Device:R", "Device:C", "Device:L"


# Passive part numbers, keyed by (kind, value, package). Anything not listed here falls
# through as a bare value, and check_design.py reports it as an unsourced BOM line -- so
# the table is self-policing: a part with no number cannot quietly reach a fab.
#
# The RF entries are not interchangeable with the generic ones. A 3 pF X7R in the matching
# network has a Q of 10-50 at 915 MHz against 300-1000 for an RF C0G, and the tolerance
# has to be +/-0.1 pF because the values themselves are that small. Likewise the block D
# inductors must be wirewound: multilayer ferrite 0402 parts run Q = 8-20 at 900 MHz,
# which is most of a dB of TX power.
PASSIVES = {
    # ceramics -- generic X7R/X5R for bypass, C0G for anything timing or RF
    ("C", "15p",  "0402"): dict(MPN="0402CG150J500NT", Manufacturer="FH", LCSC="C1548",
                                Dielectric="C0G", Tolerance="5%", Voltage="50V"),
    ("C", "10p",  "0402"): dict(MPN="CL05C100JB5NNNC", Manufacturer="Samsung", LCSC="C32949",
                                Dielectric="C0G", Tolerance="5%", Voltage="50V"),
    ("C", "39p",  "0402"): dict(MPN="CC0402JRNPO9BN390", Manufacturer="YAGEO", LCSC="C106223",
                                Dielectric="NP0", Tolerance="5%", Voltage="50V"),
    ("C", "1n",   "0402"): dict(MPN="0402B102K500NT", Manufacturer="FH", LCSC="C1523",
                                Dielectric="X7R", Tolerance="10%", Voltage="50V"),
    ("C", "47n",  "0402"): dict(MPN="0402B473K250NT", Manufacturer="FH", LCSC="C285062",
                                Dielectric="X7R", Tolerance="10%", Voltage="25V"),
    ("C", "100n", "0402"): dict(MPN="CL05B104KO5NNNC", Manufacturer="Samsung", LCSC="C1525",
                                Dielectric="X7R", Tolerance="10%", Voltage="16V"),
    ("C", "470n", "0402"): dict(MPN="CL05A474KP5NNNC", Manufacturer="Samsung", LCSC="C47339",
                                Dielectric="X5R", Tolerance="10%", Voltage="10V"),
    ("C", "1u",   "0402"): dict(MPN="CL05A105KA5NQNC", Manufacturer="Samsung", LCSC="C52923",
                                Dielectric="X5R", Tolerance="10%", Voltage="25V"),
    ("C", "4u7",  "0603"): dict(MPN="CL10A475KO8NNNC", Manufacturer="Samsung", LCSC="C19666",
                                Dielectric="X5R", Tolerance="10%", Voltage="16V"),
    # RF: C0G, +/-0.1pF, high Q. Only the antenna-pi shunts survive the IPD, and they are
    # DNP -- but they stay specified so a tuning spin can order them without re-deriving.
    ("C", "3p9",  "0402"): dict(MPN="GJM1555C1H3R9BB01D", Manufacturer="Murata", LCSC="C76907",
                                Dielectric="C0G", Tolerance="+/-0.1pF", Voltage="50V"),
    # the one inductor left: the PA drain choke, whose DCR sits in series with the PA supply
    ("L", "47n",  "0402"): dict(MPN="LQW15AN47NG80D", Manufacturer="Murata", LCSC="C237556",
                                Tolerance="2%", Description="wirewound, 648mOhm, 440mA"),
    # resistors, all UNI-ROYAL 1% thin film
    ("R", "27R",  "0402"): dict(MPN="0402WGF270JTCE", Manufacturer="UNI-ROYAL", LCSC="C25100",
                                Tolerance="1%"),
    ("R", "100R", "0402"): dict(MPN="0402WGF1000TCE", Manufacturer="UNI-ROYAL", LCSC="C25076",
                                Tolerance="1%"),
    ("R", "220R", "0402"): dict(MPN="0402WGF2200TCE", Manufacturer="UNI-ROYAL", LCSC="C25091",
                                Tolerance="1%"),
    ("R", "1k",   "0402"): dict(MPN="0402WGF1001TCE", Manufacturer="UNI-ROYAL", LCSC="C11702",
                                Tolerance="1%"),
    ("R", "5k1",  "0402"): dict(MPN="0402WGF5101TCE", Manufacturer="UNI-ROYAL", LCSC="C25905",
                                Tolerance="1%", Description="USB-C Rd; 1 percent, 100ppm"),
    ("R", "10k",  "0402"): dict(MPN="0402WGF1002TCE", Manufacturer="UNI-ROYAL", LCSC="C25744",
                                Tolerance="1%"),
}


def _passive(kind, val, fp, extra=None):
    """Merge the catalogue entry for a passive into its schematic properties."""
    pkg = fp.rsplit("_", 1)[0].rsplit("_", 1)[-1]
    props = dict(PASSIVES.get((kind, val, pkg), {}))
    if extra:
        props.update(extra)
    return props


def cap(ref, x, y, val, fp=FP["C"], angle=0, props=None, **kw):
    s.place(ref, C_, x, y, value=val, footprint=fp, angle=angle,
            props=_passive("C", val, fp, props), **kw)


def res(ref, x, y, val, dnp=False, angle=0, props=None, **kw):
    s.place(ref, R_, x, y, value=val, footprint=FP["R"], dnp=dnp, angle=angle,
            props=_passive("R", val, FP["R"], props), **kw)


def ind(ref, x, y, val, angle=0, fp=None, props=None, **kw):
    fp = fp or FP["L"]
    s.place(ref, L_, x, y, value=val, footprint=fp, angle=angle,
            props=_passive("L", val, fp, props), **kw)


def flag(ref, x, y):
    s.place(ref, "power:PWR_FLAG", x, y, in_bom=False)


def rail(ref, lib, x, y):
    s.place(ref, lib, x, y, in_bom=False)


def decouple(ref, x, y, val, node, fp=FP["C"], at=None):
    """
    A bypass cap from `node` to ground, drawn vertically.

    `at` records which pin the cap belongs to. Stacked symbol pins collapse a whole
    rail onto one schematic node, so without this the layout has no way to know that
    C3..C9 are one-per-IOVDD-pin rather than six caps that may all go on one side.
    """
    cap(ref, x, y, val, fp=fp, props={"Description": "decoupling: %s" % at} if at else None)
    s.net(node, "%s.1" % ref)
    s.net("GND", "%s.2" % ref)


def series(ref, kind, x, y, val, a, b, angle=0):
    """A series element bridging nets `a` and `b`, joined only by its labels."""
    (cap if kind == "C" else ind if kind == "L" else res)(ref, x, y, val, angle=angle)
    s.net(a, "%s.1" % ref)
    s.net(b, "%s.2" % ref)


# ================================================ A. USB-C entry, ESD, power rails
s.box(12.7, 15.24, 187.96, 154.94)
s.text(15.24, 22.86, "A  USB-C plug entry, ESD, power rails")

# J2 is a USB-C PLUG on the board: this stick IS the plug. A sink presenting a plug
# terminates CC with a single Rd; putting Rd on both CC and VCONN would show the host
# the Debug-Accessory signature instead of a device.  [usbc]
# This is a straddle-mount plug: the A row lands on F.Cu, the B row on B.Cu, and the
# board edge itself becomes the plug's tongue. So the CONNECTOR sets the stack-up --
# JAE's drawing calls for 0.8 +/-0.08 mm pad to pad. (Do not cite the USB pair as evidence
# for a stack-up: RP2040's USB is full-speed 12 Mbit/s and the run is under 25 mm, so it
# never behaves as a transmission line on any of these builds.)  [usbc]
s.place("J2", "Connector:USB_C_Plug_USB2.0", 38.1, 71.12, value="USB-C plug",
        footprint=FP["USBC"],
        props={"MPN": "DX07P024AJ1R1500", "Manufacturer": "JAE", "LCSC": "C5352764",
               "Description": "Straddle-mount USB-C plug; hand-fit after the SMT run."})
s.net("VBUS", "J2.A4")                     # A4/A9/B4/B9 are one stacked pin
s.net("GND", "J2.A1", "J2.SH")             # A1/A12/B1/B12 stacked; shell to GND
s.net("USB_CC", "J2.A5")
s.net("USB_DP_C", "J2.A6")
s.net("USB_DM_C", "J2.A7")
s.no_connect("J2.B5")                      # VCONN must read above zOPEN=126k: leave open  [usbc]
# B6/B7 are absent from a USB 2.0 plug by spec (Table 3-11 note 2) and the receptacle
# already shorts A6<->B6, so do not tie them "for symmetry" -- that is a stub on a 90 ohm
# pair. SBU1/SBU2 must read >=950k, and the SuperSpeed pads must float: grounding them
# would short the host's TX/RX. All are left off the netlist on purpose.  [usbc]

res("R11", 71.12, 78.74, "5k1")            # Rd, 5.1k 1% -- the +/-10% row of Table 4-28  [usbc]
s.net("USB_CC", "R11.1")
s.net("GND", "R11.2")

s.place("U7", "Power_Protection:USBLC6-2SC6", 106.68, 66.04, value="USBLC6-2SC6",
        footprint=FP["SOT23_6"],
        props={"MPN": "USBLC6-2SC6", "Manufacturer": "UMW", "LCSC": "C2687116"})
s.net("USB_DP_C", "U7.1")
s.net("USB_DM_C", "U7.3")
s.net("VBUS", "U7.5")
s.net("GND", "U7.2")
s.net("USB_DP_R", "U7.6")
s.net("USB_DM_R", "U7.4")
decouple("C41", 137.16, 88.9, "100n", "VBUS", at="U7 pin 5 VBUS clamp")

res("R1", 147.32, 60.96, "27R", angle=90)  # RP2040 USB series terminations  [rpi]
res("R2", 147.32, 71.12, "27R", angle=90)
s.net("USB_DP_R", "R1.1")
s.net("USB_DM_R", "R2.1")
s.net("USB_DP", "R1.2")
s.net("USB_DM", "R2.2")

rail("#PWR_VBUS", "power:VBUS", 71.12, 45.72)
s.net("VBUS", "#PWR_VBUS.1")
flag("#FLG_VBUS", 88.9, 45.72)
s.net("VBUS", "#FLG_VBUS.1")
flag("#FLG_GND", 17.78, 60.96)
s.net("GND", "#FLG_GND.1")
rail("#PWR_GND1", "power:GND", 17.78, 71.12)
s.net("GND", "#PWR_GND1.1")

# --- VBUS -> ferrite -> the two 3V3 rails ---------------------------------
# Total VBUS-to-GND capacitance is capped at 10uF by BOTH USB 2.0 (inrush, section
# 7.2.4.1) and Type-C (Table 4-3). Budget, in uF: C15 4.7 + C27 4.7 + C41 0.1 = 9.5uF.
#
# One 4u7 per LDO input rather than a separate bulk cap. TI specify CIN >= 0.7uF "over
# the full range of operating conditions" for the LP5907, and a 1uF 0402 sitting at 5-5.5V
# of DC bias can derate to 0.3-0.5uF -- under the floor. A 16V 0603 4u7 holds ~2.8uF at
# 5V, and putting one at each regulator also satisfies TI's "not more than 1 cm from the
# input pin", which a shared bulk cap at the connector would not.
#
# There is deliberately no ferrite between the plug and the LDOs. One was fitted in Rev A
# when 44uF sat behind it; with the bulk cut to spec the bead's 0.6-1.6uH against 2uF
# became a 90-145kHz tank damped only by its own DCR, and a hot-plug step would ring
# 13-49% above 5V -- past the LP5907's 6.0V absolute maximum.  [usbc]

s.place("U5", "Regulator_Linear:ME6211C33M5", 111.76, 116.84, value="ME6211C33M5G",
        footprint=FP["SOT23_5"],
        props={"MPN": "ME6211C33M5G-N", "Manufacturer": "Microne", "LCSC": "C82942"})
s.net("VBUS", "U5.1", "U5.3")            # CE tied to VIN: always on
s.net("GND", "U5.2")
s.net("+3V3", "U5.5")
s.no_connect("U5.4")
decouple("C15", 91.44, 132.08, "4u7", "VBUS", fp=FP["C0603"], at="U5 pin 1 VIN")
decouple("C16", 137.16, 132.08, "1u", "+3V3")
decouple("C18", 157.48, 132.08, "4u7", "+3V3", fp=FP["C0603"])
rail("#PWR_3V3A", "power:+3V3", 177.8, 116.84)
s.net("+3V3", "#PWR_3V3A.1")

s.place("U6", "Regulator_Linear:LP5907MFX-3.3", 111.76, 152.4, value="LP5907MFX-3.3",
        footprint=FP["SOT23_5"],
        props={"MPN": "LP5907MFX-3.3/NOPB", "Manufacturer": "Texas Instruments",
               "LCSC": "C80670",
               "Description": "Genuine TI part only. The LCSC clones are 50uVrms and "
                              "70dB PSRR against 10uVrms and 82dB for the TI part -- a "
                              "clone turns U6 into a second ME6211 and deletes the "
                              "reason it exists."})
s.net("VBUS", "U6.1", "U6.3")
s.net("GND", "U6.2")
s.net("+3V3_RF", "U6.5")
s.no_connect("U6.4")
decouple("C17", 137.16, 167.64, "1u", "+3V3_RF")
decouple("C19", 157.48, 167.64, "4u7", "+3V3_RF", fp=FP["C0603"])
decouple("C27", 91.44, 167.64, "4u7", "VBUS", fp=FP["C0603"], at="U6 pin 1 VIN")
rail("#PWR_RFA", "zach:+3V3_RF", 177.8, 152.4)
s.net("+3V3_RF", "#PWR_RFA.1")

# ================================================== B. RP2354A, crystal, buttons
s.box(208.28, 15.24, 210.82, 279.4)
s.text(210.82, 22.86, "B  RP2354A (2MB flash in package), crystal, buttons")

# RP2354A, not RP2040: same die as RP2350A with a Winbond W25Q16JVWI 2MB flash die stacked
# in the package. That deletes the external QSPI flash outright -- and with it the whole
# class of failure that made us reject the GD25Q32E, where a flash that only accepts a
# one-byte 01h status-register write cannot have its quad-enable bit set by the stock
# boot2 and faults out of boot after happily enumerating.
#
# Pin 61, the centre pad, is again the ONLY ground connection, so the footprint carries
# its own vias. RP2354A has no TESTEN pin.
#
# 2MB is enough, measured not assumed: Meshtastic's pico2 image is 978,688 B against
# 1,536 kB of sketch space with the standard 0.5 MB LittleFS -- 62% used.
s.place("U1", "MCU_RaspberryPi:RP2354A", 281.94, 132.08, value="RP2354A",
        footprint=FP["RP2354"],
        props={"MPN": "RP2354A", "Manufacturer": "Raspberry Pi", "LCSC": "C41378174",
               "Description": "RP2350A + 2MB stacked flash, QFN-60 7x7 0.4mm. Confirm the "
                              "die stepping on receipt: E9 (GPIO input latch) is A2-only "
                              "and fixed in A3; DigiKey ships A4, LCSC does not publish it."})

s.net("+3V3", "U1.1", "U1.44", "U1.53", "U1.54")   # IOVDD(x6 stacked), ADC_AVDD, USB_OTP_VDD, QSPI_IOVDD
s.net("GND", "U1.61", "U1.47")                     # exposed pad + VREG_PGND
s.net("USB_DM", "U1.51")
s.net("USB_DP", "U1.52")
s.net("RUN", "U1.26")

# 100nF per supply pin. QSPI_IOVDD gets its own rather than sharing: on RP2354 it feeds
# the internal flash die, must be 2.97-3.63 V, and carries that die's switching currents.
for ref, x, pin in [("C3", 218.44, "IOVDD pin 1"), ("C4", 233.68, "IOVDD pin 11"),
                    ("C5", 248.92, "IOVDD pin 20"), ("C6", 264.16, "IOVDD pin 30"),
                    ("C8", 279.4, "IOVDD pin 38"), ("C9", 294.64, "IOVDD pin 45"),
                    ("C44", 309.88, "ADC_AVDD pin 44"),
                    ("C12", 325.12, "USB_OTP_VDD pin 53"),
                    ("C45", 340.36, "QSPI_IOVDD pin 54 - internal flash die")]:
    decouple(ref, x, 40.64, "100n", "+3V3", at=pin)

# The core supply is a BUCK on RP2350, not the simple LDO RP2040 had. VREG_LX switches
# into L2 and the output is the DVDD rail; VREG_FB senses it. Raspberry Pi are
# prescriptive about the parts: 3.3uH +/-20% fully shielded, DCR <= 250 mOhm,
# Isat >= 1.5 A, and 4.7uF at the input, the output and on VREG_AVDD.
# DVDD and VREG_AVDD reach the chip through a passive (L2, R16), so ERC cannot see a
# driver on either. Flag them rather than switch the rule off.
flag("#FLG_DVDD", 297.18, 76.2)
flag("#FLG_VAVDD", 406.4, 78.74)
res("R16", 388.62, 96.52, "33R")                   # VREG_AVDD RC filter, ~200uA load
s.net("+3V3", "R16.1")
s.net("VREG_AVDD", "R16.2", "U1.46", "#FLG_VAVDD.1")
decouple("C47", 388.62, 116.84, "4u7", "VREG_AVDD", fp=FP["C0603"], at="VREG_AVDD pin 46")
decouple("C46", 355.6, 40.64, "4u7", "+3V3", fp=FP["C0603"], at="VREG_VIN pin 49")
s.net("+3V3", "U1.49")
ind("L2", 370.84, 40.64, "3u3", angle=90, fp=FP["L3012"],
    props={"MPN": "MPN3012S3R3MT", "Manufacturer": "Cenker", "LCSC": "C52024124",
           "Description": "RP2350 core buck inductor: 3.3uH +/-20% shielded, 135mOhm, "
                          "Isat 1.7A. Polarity/orientation per the datasheet. VERIFY the "
                          "land pattern against the MPN3012S drawing before fab -- the "
                          "footprint here is a generic 3012 land."})
s.net("VREG_LX", "U1.48", "L2.1")
s.net("DVDD", "U1.6", "U1.50", "L2.2", "#FLG_DVDD.1")   # DVDD(x3) + VREG_FB sense
for ref, x, pin in [("C7", 218.44, "DVDD pin 6"), ("C42", 233.68, "DVDD pin 23"),
                    ("C43", 248.92, "DVDD pin 39")]:
    decouple(ref, x, 60.96, "100n", "DVDD", at=pin)
decouple("C28", 264.16, 60.96, "4u7", "DVDD", fp=FP["C0603"], at="buck output, at DVDD pin 23")

res("R5", 226.06, 96.52, "10k")                    # RUN pull-up
s.net("+3V3", "R5.1")
s.net("RUN", "R5.2")

# 12MHz crystal: 1K series on XOUT, 15p loads for a CL=10pF part  [rpi]
s.place("Y1", "Device:Crystal_GND24", 231.14, 187.96, value="12MHz CL10p",
        footprint=FP["XTAL"], props={"MPN": "ABM8-272-T3", "Manufacturer": "Abracon",
                                     "LCSC": "C20625731",
                                     "Description": "12MHz, CL=10pF -- the CL the 15p loads are sized for"})
res("R3", 254.0, 187.96, "1k")
cap("C1", 220.98, 205.74, "15p")
cap("C2", 251.46, 205.74, "15p")
s.net("XIN", "U1.21", "Y1.1", "C1.1")
s.net("XOUT_R", "Y1.3", "C2.1", "R3.1")
s.net("XOUT", "R3.2", "U1.22")
s.net("GND", "C1.2", "C2.2", "Y1.2")

# The QSPI bus still comes out to pins even though the flash die is inside -- the pads
# drive both. Raspberry Pi ask for minimal track length on them, so these are bare
# no-connect pads with no copper run anywhere. QSPI_SS is the exception: it still selects
# BOOTSEL, and 1k to ground beats the internal pull-up with margin.
s.no_connect("U1.55", "U1.56", "U1.57", "U1.58", "U1.59")
res("R4", 332.74, 246.38, "1k", angle=90)
s.net("QSPI_SS", "U1.60", "R4.1")
s.place("TP5", "Connector:TestPoint", 358.14, 246.38, value="BOOTSEL", footprint=FP["TP"],
        in_bom=False)
s.net("BOOT_SW", "R4.2", "TP5.1")

# User button on GPIO6  [chosen]
s.place("SW1", "Switch:SW_Push", 355.6, 274.32, value="USER", footprint=FP["SW"],
        props={"MPN": "TS-1187A-B-A-B", "Manufacturer": "XKB", "LCSC": "C318884"})
s.net("BTN_USER", "SW1.1", "U1.9")                 # GPIO6
s.net("GND", "SW1.2")

s.place("TP1", "Connector:TestPoint", 226.06, 246.38, value="SWCLK", footprint=FP["TP"], in_bom=False)
s.place("TP2", "Connector:TestPoint", 246.38, 246.38, value="SWDIO", footprint=FP["TP"], in_bom=False)
s.place("TP3", "Connector:TestPoint", 266.7, 246.38, value="GND", footprint=FP["TP"], in_bom=False)
s.place("TP4", "Connector:TestPoint", 287.02, 246.38, value="RUN", footprint=FP["TP"], in_bom=False)
s.net("RUN", "TP4.1")
s.place("TP6", "Connector:TestPoint", 307.34, 246.38, value="SDA", footprint=FP["TP"], in_bom=False)
s.place("TP7", "Connector:TestPoint", 327.66, 246.38, value="SCL", footprint=FP["TP"], in_bom=False)
s.net("I2C_SDA", "U1.7", "TP6.1")                  # GPIO4 = Wire0 SDA
s.net("I2C_SCL", "U1.8", "TP7.1")                  # GPIO5 = Wire0 SCL
res("R12", 307.34, 220.98, "4k7")                  # I2C is open drain: the bus cannot be
res("R13", 327.66, 220.98, "4k7")                  # released high without these
s.net("+3V3", "R12.1", "R13.1")
s.net("I2C_SDA", "R12.2")
s.net("I2C_SCL", "R13.2")
s.net("SWCLK", "U1.24", "TP1.1")
s.net("SWDIO", "U1.25", "TP2.1")
s.net("GND", "TP3.1")

# ============================================================ C. SX1262 + TCXO
s.box(429.26, 15.24, 152.4, 154.94)
s.text(431.8, 22.86, "C  SX1262 + 32MHz TCXO")

# The exposed pad is both the thermal path for ~230 mW at +22 dBm and the radio's whole
# ground return on two layers, so the footprint carries its own vias.  [semtech]
s.place("U2", "RF:SX1262IMLTRT", 490.22, 106.68, value="SX1262IMLTRT",
        footprint=FP["SX1262"],
        props={"MPN": "SX1262IMLTRT", "Manufacturer": "Semtech", "LCSC": "C191341"})

# VDD_IN (1) ties straight to VBAT (10); VBAT_IO (11) shares the SAME rail so the
# datasheet rule "VBAT_IO <= VBAT at all times" cannot be broken by LDO ramp skew.
decouple("C10", 439.42, 40.64, "100n", "+3V3_RF", at="VDD_IN/VBAT pins 1/10/11 HF")
decouple("C11", 454.66, 40.64, "1u", "+3V3_RF", at="VBAT/VBAT_IO bulk for the PA step")
decouple("C29", 469.9, 40.64, "470n", "SX_VREG")   # VREG  [ws]
decouple("C30", 485.14, 40.64, "47n", "VR_PA")     # VR_PA coarse  [ws]
decouple("C37", 500.38, 40.64, "39p", "VR_PA")     # VR_PA fine [ws]; shares C22/C32 line
s.net("+3V3_RF", "U2.1", "U2.10", "U2.11")
s.net("GND", "U2.2")
s.net("SX_VREG", "U2.7")
s.net("VR_PA", "U2.24")
# Internal-LDO mode, Option D of datasheet Fig 5-4. Meshtastic/RadioLib issue
# SetRegulatorMode(DC-DC) unconditionally with no build flag to change it, but the
# datasheet is explicit that the linear regulator backstops VREG, and Meshtastic's own
# shipping t-echo-lite variant leaves DCC_SW open the same way. The cost is 4.2 mA more
# in RX, which is free on a USB-powered stick, and it saves the 15uH inductor.  [semtech]
s.no_connect("U2.9")

# SPI1 + control  [variant]
s.net("LORA_SCK", "U2.18", "U1.18")                # GPIO14
s.net("LORA_MOSI", "U2.17", "U1.19")               # GPIO15
s.net("LORA_MISO", "U2.16", "U1.36")               # GPIO24
s.net("LORA_CS", "U2.19", "U1.17")                 # GPIO13
s.net("LORA_RST", "U2.15", "U1.35")                # GPIO23
s.net("LORA_BUSY", "U2.14", "U1.29")               # GPIO18
s.net("LORA_DIO1", "U2.13", "U1.27")               # GPIO16

# TCXO. Semtech requires a 10pF DC-cut in series with 220R into XTA, and XTB open.
# Waveshare uses a bare 0R with no DC block; follow Semtech, not Waveshare.  [semtech]
# Pin 1 of a clipped-sine TCXO is NC, not an enable -- the ASE-xxxMHz symbol this used to
# carry is an HCMOS oscillator, and driving its pin 1 high was wiring an enable that the
# real part does not have. The 2520 body is also where the cheap 32 MHz parts live.
s.place("Y2", "Oscillator:TG2520SMN-xx.xxxxxxMhz-xxxxNM", 439.42, 137.16,
        value="32MHz TCXO 3.0V clipped-sine", footprint=FP["TCXO"],
        props={"MPN": "TG2520SMN 32.000000M-MCGNNM", "Manufacturer": "Seiko Epson",
               "LCSC": "C3007516",
               "Description": "32.000MHz TCXO, clipped sine, Vcc 2.66-3.465V, Icc 1.8mA "
                              "max, start-up 2.0ms max. Program DIO3 to 3.0V: VBAT 3.3V "
                              "satisfies VBAT >= VTCXO+200mV with 300mV to spare. The "
                              "1.8V sibling ECGNNM is a trap -- RadioLib defaults "
                              "tcxoVoltage to 1.6V, below that part 1.7V minimum."})
decouple("C13", 439.42, 162.56, "100n", "VDD_TCXO")
series("R6", "R", 469.9, 129.54, "220R", "TCXO_OUT", "TCXO_AC", angle=90)
series("C40", "C", 485.14, 129.54, "10p", "TCXO_AC", "XTA", angle=90)
s.quiet_pin("C40.1")
s.net("XTA", "U2.3")
s.net("VDD_TCXO", "U2.6", "Y2.4")                  # DIO3 is a programmable LDO
s.no_connect("Y2.1")                               # NC on a TCXO: open or GND, never driven
s.net("TCXO_OUT", "Y2.3")
s.net("GND", "Y2.2")
s.no_connect("U2.4")                               # XTB left open with a TCXO  [semtech]
flag("#FLG_TCXO", 515.62, 162.56)
s.net("VDD_TCXO", "#FLG_TCXO.1")

# ====================================================== D. RF front end (915MHz)
s.box(12.7, 302.26, 447.04, 101.6)
s.text(15.24, 309.88,
       "D  Johanson IPD front end + SPDT antenna switch    902-928MHz")

# The discrete matching network is gone. What was here was Semtech's SX1261 topology being
# run at +22 dBm - two elements short of their SX1262 network - with values taken from a
# licensee's schematic and never validated. FL1 replaces the TX filter AND the RX balun
# with one LTCC part whose response is fixed in ceramic and factory-tested.
#
# The K variant, not the D. 2f0 (1804-1856 MHz) is NOT in an FCC restricted band and needs
# only 20 dBc, but 3f0 (2706-2784), 4f0 (3608-3712) and 5f0 (4510-4640) all are and need
# ~63 dB. The D part specifies nothing above 3f0; the K specifies all three.
#
# DigiKey only - Johanson is not in LCSC's catalogue - so this part is consigned or hand
# placed if the board goes to JLCPCB assembly.
RFFP = dict(R=FP["R"], C=FP["C"], L=FP["L"])
TXY = 342.9

ind("L1", 40.64, TXY, "47n", angle=90)             # PA drain choke, VR_PA -> RFO
s.net("VR_PA", "L1.1")
s.net("RFO", "L1.2", "U2.23")

s.place("FL1", "Filter:0900FM15K0039", 88.9, TXY, value="0900FM15K0039001E",
        footprint=FP["IPD"],
        props={"MPN": "0900FM15K0039001E", "Manufacturer": "Johanson Technology",
               "DigiKey": "712-0900FM15K0039001ETR-ND",
               "Description": "SX1262 front-end IPD: TX filter + RX balun, 902-928MHz, "
                              "IL 1.1dB TX / 1.4dB RX max, 2W CW. NOT the D variant."})
s.net("RFO", "FL1.1")
s.net("RFI_N", "FL1.3", "U2.22")
s.net("RFI_P", "FL1.4", "U2.21")
s.net("GND", "FL1.2")                              # pins 2/5/7/9/10 stacked in the symbol

# pSemi require the switch's RF ports be DC blocked. Johanson's reference puts no block
# between the IPD and the switch, but they do not state that their switch ports are
# DC-free, so these stay until that is answered. They reuse the existing 39p line item.
series("C22", "C", 129.54, 330.2, "39p", "IPD_TX", "RF_TX", angle=90)
series("C25", "C", 129.54, 373.38, "39p", "IPD_RX", "RF_RX", angle=90)
s.net("IPD_TX", "FL1.8")
s.net("IPD_RX", "FL1.6")

# --- SPDT switch, complementary control  [variant] -------------------------
s.place("U4", "zach:PE4259-63", 190.5, 358.14, value="PE4259-63", footprint=FP["SC70_6"],
        props={"MPN": "PE4259-63", "Manufacturer": "pSemi", "LCSC": "C470892"})
s.net("RF_TX", "U4.1")                             # RF1 = TX  [semtech]
s.net("RF_RX", "U4.3")                             # RF2 = RX
s.net("RF_ANT", "U4.5")
s.net("GND", "U4.2")
series("R7", "R", 165.1, 325.12, "100R", "RF_SW_CTRL", "SW_CTRL", angle=90)
series("R8", "R", 165.1, 388.62, "100R", "RF_SW_NCTRL", "SW_NCTRL", angle=90)
s.net("SW_CTRL", "U4.4")
s.net("SW_NCTRL", "U4.6")
decouple("C35", 218.44, 320.04, "1n", "SW_CTRL")
decouple("C36", 218.44, 393.7, "1n", "SW_NCTRL")
s.net("RF_SW_CTRL", "U2.12")                       # DIO2 drives CTRL
s.net("RF_SW_NCTRL", "U1.28")                      # GPIO17 drives the complement

# --- antenna feed ----------------------------------------------------------
# The K variant already carries the harmonic filtering the discrete antenna pi provided,
# so the pi is not fitted. Its lands stay as a tuning option: R15 is a 0R link in the
# series position and C33/C34 are unpopulated. If the FCC pre-scan needs more suppression
# at 3f0-5f0, fit 9n1 in place of R15 and populate the shunts.
ant = Chain(s, 266.7, TXY, RFFP, catalogue=_passive)
ant.series("C32", "C", "39p", "RF_ANT", "ANT1")    # DC block off RFC
ant.series("R15", "R", "0R", "ANT1", "ANT2")       # pi series position, linked out
ant.shunt("C33", "C", "3p9", "ANT1", dnp=True)
ant.shunt("C34", "C", "3p9", "ANT2", dnp=True)

# A real SMA jack on the board, not u.FL and not an edge-clamp launch.
#
# The earlier note here said board-edge SMAs were ruled out because the Taoglas
# EMPCB.SMAFSTJ.B.HT "caps at 0.79 mm". That was a misreading: its specification table
# says 0.8 mm and only the footprint page says 0.79, and 0.79 mm IS 0.031 in -- the
# number the whole industry uses for a 0.8 mm board, not a machined cliff.
#
# The real objection to an edge launch is different and applies to every one of them:
# tightening an SMA to its own spec torque (0.57 N.m) puts roughly 134 MPa of shear into
# a 20 mm x 0.8 mm FR-4 strip, which is past FR-4's shear strength. The whip's weight is
# irrelevant -- safety factor around 130 -- but the mating torque is not.
#
# BWSMA-KWE-Z001 sidesteps both. Its four ground legs and centre pin are THROUGH HOLE, so
# the mating torque is carried by plated barrels through all four layers instead of by
# surface pads or a clamp on a 0.8 mm edge, and board thickness stops being a parameter
# at all. It is a right-angle jack, so the antenna axis lies in the board plane, which is
# what a stick wants. LCSC stocks it 130k deep at $0.51 against $3.75-4.01 for the edge
# launches, and KiCad already ships the footprint.
#
# It is a standard SMA FEMALE jack, not RP-SMA: Meshtastic whips are SMA male.
s.place("J1", "Connector:Conn_Coaxial", 327.66, TXY, value="SMA",
        footprint=FP["SMA"],
        props={"MPN": "BWSMA-KWE-Z001", "Manufacturer": "BAT Wireless", "LCSC": "C496551",
               "Description": "SMA(F) right-angle jack, through-hole. Hand-fit after "
                              "reflow. The enclosure should still capture the body so "
                              "repeated mating torque does not load the board alone."})
s.net("ANT2", "J1.1")
s.net("GND", "J1.2")

# ================================================ E. Status LEDs
s.box(12.7, 177.8, 187.96, 114.3)
s.text(15.24, 185.42, "E  Status LEDs: heartbeat and radio activity")

# Two plain LEDs, not the SK9822 this carried before. Upstream Meshtastic drives LED_POWER
# (a 1 ms heartbeat once a second) and LED_LORA (solid through TX, 100 ms on each received
# packet) from single GPIOs with nothing but a #define -- there is no APA102/SK9822 driver
# in the tree at all, and AmbientLightingThread only knows NCP5623, LP5562 and NeoPixel.
# This also deletes the board's only 4.5-5.5 V logic domain and its only part with under
# 500 pieces of distributor stock.
s.place("D1", "Device:LED", 63.5, 213.36, value="green", footprint=FP["LED"], angle=180,
        props={"MPN": "XL-1608SYGC-06", "Manufacturer": "XINGLIGHT", "LCSC": "C965805"})
res("R9", 78.74, 213.36, "470R", angle=90)
s.net("LED_PWR", "U1.4", "D1.2")                   # GPIO2 -> anode, LED_POWER heartbeat
s.net("LED_PWR_K", "D1.1", "R9.1")                 # cathode -> 1k -> GND
s.net("GND", "R9.2")
s.quiet_pin("R9.1")

s.place("D2", "Device:LED", 63.5, 241.3, value="red", footprint=FP["LED"], angle=180,
        props={"MPN": "KT-0603R", "Manufacturer": "Hubei KENTO", "LCSC": "C2286"})
res("R10", 78.74, 241.3, "470R", angle=90)
s.net("LED_LORA", "U1.5", "D2.2")                  # GPIO3 -> anode, LED_LORA activity
s.net("LED_LORA_K", "D2.1", "R10.1")               # cathode -> 1k -> GND
s.net("GND", "R10.2")
s.quiet_pin("R10.1")

# Unused GPIOs get an explicit no-connect so ERC stays meaningful.
# RP2354A GPIO pin numbers (QFN-60): GPIO0..29 land on these package pins.
ALL_GPIO_PINS = [2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19,
                 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43]
USED_GPIO_PINS = {4, 5, 7, 8, 9, 17, 18, 19, 27, 28, 29, 35, 36}
for pin in ALL_GPIO_PINS:
    if pin not in USED_GPIO_PINS:
        s.no_connect("U1.%d" % pin)

if __name__ == "__main__":
    out = pathlib.Path(__file__).parent / "mesh.kicad_sch"
    errs, warns = s.write(out)
    print("wrote %s  (%d placements, %d connections)" % (out.name, len(s.parts), len(s.conns)))
    for e in errs:
        print("  ERROR  ", e)
    for w in warns:
        print("  warn   ", w)
    import json
    (pathlib.Path(__file__).parent / "intended_netlist.json").write_text(
        json.dumps(s.intended_netlist(), indent=1))
    sys.exit(1 if errs else 0)
